# Generated by Django 3.1.1 on 2020-09-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauracja_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauracja',
            name='adres',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='restauracja',
            name='nazwa',
            field=models.TextField(max_length=128),
        ),
    ]
