# Generated by Django 3.1.1 on 2020-09-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restauracja_app', '0002_auto_20200913_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restauracja',
            old_name='adres',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='restauracja',
            old_name='nazwa',
            new_name='name',
        ),
    ]
