# Generated by Django 3.1.1 on 2020-09-13 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restauracja_app', '0004_typ'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Typ',
            new_name='Type',
        ),
        migrations.AddField(
            model_name='restauracja',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restauracja_app.type'),
        ),
    ]
